# Generated by Django 3.1.3 on 2020-11-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201125_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('zip_code',), 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
